services:
  # Backend API service
  - type: web
    name: document-processor-api
    env: python
    region: oregon # You can change this to a region closer to your users
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: METADATA_BUCKET
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_CLOUD
        sync: false
      - key: PINECONE_REGION
        sync: false
      - key: PINECONE_INDEX
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://document-processor-frontend.onrender.com
      - key: ALLOW_DEV_FALLBACK
        value: "false"

  # Frontend static site
  - type: web
    name: document-processor-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://document-processor-api.onrender.com # This should match your backend URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 